name: env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - branca=0.8.2=pyhd8ed1ab_0
  - brotlicffi=1.1.0.0=py313h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py313h02ab6af_1
  - charset-normalizer=3.4.4=py313haa95532_0
  - expat=2.7.3=h9214b88_0
  - folium=0.20.0=pyhd8ed1ab_0
  - glib=2.84.0=h3d4babf_0
  - glib-tools=2.84.0=h4394cf3_0
  - gst-plugins-base=1.24.7=hb0a98b8_0
  - gstreamer=1.24.7=h5006eae_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=py313haa95532_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - krb5=1.21.3=hdf4eb48_0
  - libblas=3.9.0=39_hf2e6a31_mkl
  - libcblas=3.9.0=39_h2a3cdd5_mkl
  - libclang13=21.1.5=default_ha2db4b5_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.0=h7025463_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=39_hf9ab0e9_mkl
  - libmpdec=4.0.0=h827c3e9_0
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.50=h7351971_1
  - libsqlite=3.51.0=hf5d6505_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.5=h4fa8253_2
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.3=py313hd650c13_0
  - mkl=2025.3.0=hac47afa_454
  - numpy=2.3.4=py313hce7ae62_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.44=h99c9b8b_2
  - pip=25.3=pyhc872135_0
  - ply=3.11=pyhd8ed1ab_3
  - pycparser=2.23=py313haa95532_0
  - pyqt=5.15.11=py313h1048830_2
  - pyqt5-sip=12.17.0=py313hfe59770_2
  - pyqtwebengine=5.15.11=py313hbf4b574_2
  - pysocks=1.7.1=py313haa95532_1
  - python=3.13.9=h260b955_100_cp313
  - python_abi=3.13=1_cp313
  - qt-main=5.15.15=h9151539_3
  - qt-webengine=5.15.15=h087ee03_1
  - requests=2.32.5=py313haa95532_1
  - setuptools=80.9.0=py313haa95532_0
  - sip=6.10.0=py313hfe59770_1
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd8ed1ab_2
  - tomli=2.3.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py313haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_1
  - xyzservices=2025.10.0=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - docopt==0.6.2
      - pipreqs==0.4.13
      - yarg==0.1.10
prefix: C:\Users\David\anaconda3\envs\env
